logo = "/uploads/surferhandy-logo.png"
icon = "/uploads/surferhandy-favicon-1-32x32.png"
tagline = "Your Source For Every Handy Advice"
contacteMail = ""

[amznTracking]
global = ""
topProducts = ""
table = ""
review = ""

[siteRobots]
pageIndex = true

[open_graph]
meta_Description = "Build Your Dreams with Wood and get Amazing ultimate guide. We cover everything about wood and help worker around the world."
image = "/uploads/surferhandy-logo.png"

[social_accounts]
sitefbAccount = ""
sitetwitterAccount = ""
siteinstagramAccount = ""
sitepinterestAccount = ""
siteYouTubeAccount = ""

[post_setting]
featured_img = false
show_comments = true

[home_setting]
footerText = ""
headerText = ""
blogSection = true
headerStyle = "Style 2"